### ISSUE TITLE
Multi zone auto

### ISSUE THREAD

**Issue by rhgiter** [Sdahl1234/Adano-lawn-mower#12]
Multi zone auto

fik du den til at virke hos dig?

hos mig slukker den lige efter jeg har tændt den.

ps. tak for tidsstyring on/off 

![image](https://github.com/Sdahl1234/Adano-lawn-mower/assets/61065752/4e8695ed-9319-4a99-8bd6-7a964e6f6b6f)

**Comment by Sdahl1234** [comment]
Nej, Den "slukker" også bare. 
Måske er det fordi vores modeller ikke understøtter det.

**Comment by rhgiter** [comment]
Hej 

jeg har lavet denne, som skulle virke

````
alias: Plæaneklipper random starttid
description: ""
trigger:
  - platform: time
    at: "06:00:00"
condition: []
action:
  - service: number.set_value
    target:
      entity_id: number.plaeneklipper_zone_1_start
    data:
      value: "{{ (0, 10, 25, 35, 45, 55, 65, 75, 85, 95, 100)|random }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: number.set_value
    target:
      entity_id: number.plaeneklipper_zone_2_start
    data:
      value: "{{ (0, 10, 25, 35, 45, 55, 65, 75, 85, 95, 100)|random }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: number.set_value
    target:
      entity_id: number.plaeneklipper_zone_3_start
    data:
      value: "{{ (0, 10, 25, 35, 45, 55, 65, 75, 85, 95, 100)|random }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: number.set_value
    target:
      entity_id: number.plaeneklipper_zone_4_start
    data:
      value: "{{ (0, 10, 25, 35, 45, 55, 65, 75, 85, 95, 100)|random }}"
mode: single

````
